### PR TITLE
Add try macro without return type adjustment

### LINKED ISSUE #6: Add `#[try]` that does Ok-wrapping but doesn't remove `Result` from function signature
Fehler was a good experiment in Ok-wrapping but I think that removing `Result` and `Option` is a bit too much. This view is also reflected by withoutboats' article in [The registers of Rust](https://without.boats/blog/the-registers-of-rust/), where it is said:

> I've written before about why I think ["Ok" wrapping](https://without.boats/blog/why-ok-wrapping/) functions would be a very good addition to Rust, and even [implemented them as well](https://github.com/withoutboats/fehler). The only way my view has evolved since then (and here I think I am now more in line with the Rust project) is that using a syntax like try fn that doesn’t change the return type, so you can specify Option or Result, is probably the right approach for Rust. But overall having a syntax that keeps the user fully inside the effect (which is what Ok-wrapping really means), rather than halfway, would be not only more convenient but also more consistent with asynchrony and iteration.

I'm not proposing changing the `#[throws]` macro but instead defining a new macro that does not change the return type. And maybe it should be called `#[try]`, with the understanding that `#[try] fn f() -> Result<i32>` could eventually become `try fn f() -> Result<i32>` if Ok-wrapping ever became part of the Rust proper.

### PR DESCRIPTION
**Pull request by Nemo157**
fixes #6

### CODE REVIEW

**Comment by Nemo157** [comment]
@dlight unfortunately `try` is a keyword so can't be used as a macro name, I've used `try_` but do you have any other suggestions?

**Comment by dlight** [comment]
Hey, thank you for that!

Here are some ideas:

* `#[try_fn]`

* `#[r#try]` (not sure if this works)

But `#[try_]` isn't too bad!

**Comment by tipsypastels** [comment]
`#[tries]`? Mirrors `#[throws]`in that they're both indicative verbs.

**Comment by Nemo157** [comment]
`#[try_fn]` was also suggested on discord when I asked about it there. I'm partial to that because it has good parallels with `#[try_expr]` that I'll add to #9 too.

**Pull request merged**
